export const LOAD_TRACKS_SUCCESS = 'LOAD_TRACKS_SUCCESS';
export const RESET_MARKER_SIZE = 'RESET_MARKER_SIZE';
export const OPEN_INFO_BOX = 'OPEN_INFO_BOX';
export const CLOSE_INFO_BOX = 'CLOSE_INFO_BOX';
export const CALCULATE_ANIMATION_COORDINATES = 'CALCULATE_ANIMATION_COORDINATES';
export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
